issues:
  exclude-use-default: false
linters:
  enable:
    - staticcheck
    - gosec
  disable:
    - deadcode
    - unused
    - gosimple
linters-settings:
  staticcheck:
    go: "1.17"
    checks: ["all"]
