outputs:
  greet:
    value: ${{ steps.show.outputs.greet }}
runs:
  using: composite
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: cat greet
      shell: bash
    - uses: show
      id: show
      run: |
        echo "greet=$(cat greet)" >> $GITHUB_OUTPUT
      shell: bash
