outputs:
  greet:
    value: ${{ steps.show.outputs.greet }}
runs:
  using: composite
  steps:
    - run: ls -l
      working-directory: ${{ github.action_path }}
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: cat greet
      shell: bash
    - id: show
      run: |
        echo "greet='$(cat greet)'" >> $GITHUB_OUTPUT
      shell: bash
