on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'select existing branch'
        required: true
        default: "main"

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: show inputs parameter
        run: |
          echo ${{ github.event.inputs.branch }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: check
        run: |
          git branch --contains
    
