name: Concurrency Sample 1

on:
  push:
  pull_request:

concurrency:
  group: 'concurrencysample1'

jobs:
    sample:
        runs-on: 'ubuntu-20.04'
        steps:
            - name: 'sleep'
              run: 'sleep 182'