name: tritter issue
 
on:
    issues:
        types: [opened, reopened, labeled]

jobs:
  issued:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
        - name: Run
          run: |
            echo ${{ github.event.issue.title}}
            echo ${{ github.event.issue.labels}}
            echo ${{ github.event.issue.body}}
