 name: create json w/input
 
 on:
   workflow_dispatch:
     inputs:
       json:
         description: 'json input'
         required: true
 
 jobs:
   hello_job:
     runs-on: ubuntu-latest
     steps:
       - run: echo "hello, ${{ github.event.inputs.json }}"
