 name: create json w/input
 
 on:
   workflow_dispatch:
     inputs:
       json:
         description: 'json input'
         required: true
 
 jobs:
   create-json:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3
      - name: create file
        run: |
          echo '${{ github.event.inputs.json }}' | jq > gas.json
      - name: check diff
        id: diff
        run: |
          git add -N gas.json
          git diff --exit-code --quiet
        continue-on-error: true
      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo' # タイムゾーン指定
        run: echo "CURRENT_UNIX=$(date +%s)" >> $GITHUB_ENV
      - name: Commit & Push
        if: steps.diff.outcome == 'failure' # diff がある場合のみ実行する
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git switch -c feat/update-file-${{env.CURRENT_UNIX}}
          git add gas.json
          git commit -m "Update gas.json"
          git status
          git push -u origin HEAD:feat/update-file-${{env.CURRENT_UNIX}}
          gh pr create \
            --title "Update file" \
            --body "auto generate" \
            --base "main" 
        env:
          GH_TOKEN: ${{ github.token }}
