name: multi line
on:
    push:

jobs:
    do:
        runs-on: ubuntu-latest
        steps:
            - name: run
              run: echo "
                --xxx
                --yyy
                "