name: multi line
on:
    push:

jobs:
    do:
        runs-on: ubuntu-latest
        steps:
            - name: run
              run: aws s3 ls \
                s3://my-bucket \
                --recursive \
                --human-readable 
    do2:
        runs-on: ubuntu-latest
        steps:
            - name: run
              run: aws s3 ls \s3://my-bucket \--recursive \--human-readable 