name: Go test&lint

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: blck-snwmn/github-playground/.github/actions/gosetup@main
      - name: Run test
        run: |
          go test ./... --shuffle on
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: blck-snwmn/github-playground/.github/actions/gosetup@main
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
