on:
  workflow_call:
    inputs:
      template:
        type: string
      from:
        type: string
      to:
        type: string
jobs:
  git-pr-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # git-pr-release needs the git histories
      - name: use default template
        uses: actions/github-script@v6
        if: ${{ inputs.template == '' }}
        with:
          script: |
            core.exportVariable('TEMPLATE', 'Release <%= Time.now %>\n<% pull_requests.each do |pr| -%>\n<%=  pr.to_checklist_item %>\n<% end -%>')
      - name: use inputs.template
        if: ${{ inputs.template != '' }}
        run: |
          echo "TEMPLATE=${{ inputs.template }}" >> $GITHUB_ENV
      - name: show
        run: |
          echo "${{ env.TEMPLATE }}"
      # - name: test
      #   run: |
      #     echo "${{ env.TEMPLATE }}" > .git-pr-release.erb
      # - uses: actions/setup-ruby@v1
      #   with:
      #     ruby-version: 3.1
      # - run: gem install --no-document git-pr-release
      # - run: git-pr-release --squashed
      #   env:
      #     GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GIT_PR_RELEASE_BRANCH_PRODUCTION: ${{ inputs.to }}
      #     GIT_PR_RELEASE_BRANCH_STAGING: ${{ inputs.from }}
      #     GIT_PR_RELEASE_LABELS: pr-release
      #     GIT_PR_RELEASE_TEMPLATE: .git-pr-release.erb
      #     TZ: Asia/Tokyo