on:
  workflow_call:
    inputs:
      template:
        type: string
      from:
        required: true
        type: string
      to:
        required: true
        type: string
jobs:
  git-pr-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # git-pr-release needs the git histories
      - name: use default template
        if: ${{ inputs.template == '' }}
        run: |
          echo -e "Release <%= Time.now %>\n<% pull_requests.each do |pr| -%>\n<%=  pr.to_checklist_item %>\n<% end -%>" > .git-pr-release.erb
      - name: use inputs.template
        if: ${{ inputs.template != '' }}
        run: |
          echo "${{ inputs.template }}" > .git-pr-release.erb
      - name: show file
        run: |
          cat .git-pr-release.erb
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - run: gem install --no-document git-pr-release
      - run: git-pr-release --squashed
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: ${{ inputs.to }}
          GIT_PR_RELEASE_BRANCH_STAGING: ${{ inputs.from }}
          GIT_PR_RELEASE_LABELS: pr-release
          GIT_PR_RELEASE_TEMPLATE: .git-pr-release.erb
          TZ: Asia/Tokyo